{{- if not .Values.surrealdb.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "knowhow.fullname" . }}-surrealdb
  labels:
    {{- include "knowhow.labels" . | nindent 4 }}
type: Opaque
stringData:
  user: {{ .Values.surrealdb.user | quote }}
  password: {{ .Values.surrealdb.password | quote }}
{{- end }}
---
{{- if and (or .Values.apiKeys.openaiApiKey .Values.apiKeys.anthropicApiKey) (not .Values.apiKeys.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "knowhow.fullname" . }}-api-keys
  labels:
    {{- include "knowhow.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.apiKeys.openaiApiKey }}
  openai-api-key: {{ .Values.apiKeys.openaiApiKey | quote }}
  {{- end }}
  {{- if .Values.apiKeys.anthropicApiKey }}
  anthropic-api-key: {{ .Values.apiKeys.anthropicApiKey | quote }}
  {{- end }}
{{- end }}
