{{- if not .Values.surrealdb.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "memcp.fullname" . }}-surrealdb
  labels:
    {{- include "memcp.labels" . | nindent 4 }}
type: Opaque
stringData:
  user: {{ .Values.surrealdb.user | quote }}
  password: {{ .Values.surrealdb.password | quote }}
{{- end }}
